title: MAGI//ARCHIVE
description: Discovered repositories from the open source frontier
repository: xiaochunkun/repo_post
future: true
baseurl: "/repo_post"
url: "https://xiaochunkun.github.io"
remote_theme: pages-themes/minimal@v0.2.0
author:
  name: xiaochunkun
  url: https://github.com/xiaochunkun
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

